### ISSUE TITLE
Notebook loading error

### ISSUE THREAD

**Issue by cs-mshah** [lancedb/lance-deeplearning-recipes#24]
Got the following on loading the converting ImageFolder to lance notebook:

![image](https://github.com/lancedb/lance-deeplearning-recipes/assets/56499208/8d4352fe-5361-4875-b492-ff10a189c2f8)

**Comment by cs-mshah** [comment]
https://colab.research.google.com/drive/12RjdHmp6m9_Lx7YMRiat4_fYWZ2g63gx?usp=sharing

**Comment by tanaymeh** [comment]
@vipul-maheshwari Can you please look into this? I believe you have the permissions to this.

**Comment by viplismism** [comment]
@tanaymeh looking into this!

**Comment by viplismism** [comment]
@cs-mshah can you check it now? it's fixed!
Thanks for letting us know..

Here is the link for the reference : 
https://colab.research.google.com/drive/12RjdHmp6m9_Lx7YMRiat4_fYWZ2g63gx?usp=sharing

**Comment by tanaymeh** [comment]
Notebook seems to be working. Closing this.
